version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.crt:/etc/nginx/ssl/cert.crt
      - ./cert.key:/etc/nginx/ssl/cert.key

